Update menu

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -11,6 +11,26 @@ addRecord() {
 
 	echo $userName:$userAddress:$userPhone:$userEmail >> database.txt
 }
+
+#Function finds one or more records in database
+find(){
+DATABASE="database.txt"
+
+echo "Enter a record to find: "
+read input
+
+RECORD=$(grep -i $input $DATABASE)
+
+for line in "$RECORD"
+do
+	if [ $? == 1 ]; #a '1' indicates that no matches were found
+		echo "Could not find the requested record"
+	else
+		echo "Found the requested record: $line"
+	fi
+done
+}
+
 # Function updates record user
 update(){
 read -p "Please enter the first and last name on the file you wish to remove: " firstName
